server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/learn_english?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root

# MyBatis配置
mybatis:
    mapperLocations: classpath:mappers/**/*.xml
    configLocation: classpath:mybatis.xml

shiro:
  loginUrl: /unauthorication



---
spring:
  profiles: dev
  thymeleaf:
          cache: false
debug: false

---
spring:
  profiles: pro
  thymeleaf:
    cache: true
debug: false